# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfeaee550a98f690d74f9e223845df0abeebcce2120c19b5519a74ba5dfe977f5f1b21ea1c3212caa2391f0ff26987c7d36284538e3d2a8a63cdb64f9d3eafa9

test:
  secret_key_base: b834e982e31685475cd6ff43628c7eed2f2cd86012c6c5ccde26cbdb18800dd923af2b1bd7fcb60f464f95908ae243ed307e931ab0ca19dbe062dc973482b75e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
